version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./backend/node_modules:/usr/docker-container/kbc/backend/node_modules
      - ./backend:/usr/docker-container/kbc/backend
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/node_modules:/usr/docker-container/kbc/frontend/node_modules
      - ./frontend:/usr/docker-container/kbc/frontend

