version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./node_modules:/usr/docker-container/kbc/node_modules
      - .:/usr/docker-container/kbc
    stdin_open: true # Keeps standard input open for debugging
    tty: true        # Allocates a pseudo-TTY
